Add GPU counter page for IMG
google/agi pull request #619
Opened 2021-01-05 21:57 UTC by rschiu

2021-01-05 22:51 UTC, jakon2048 requested changes
Requested some changes, otherwise lgtm

2021-01-05 22:51 UTC, jakon2048 commented on _data/nav.yml
> +      - title: IMG® Counters
Imagination® PowerVR™

2021-01-05 22:51 UTC, jakon2048 commented on gpu-counters.md
> +* [IMG Counters](img)
Imagination Counters

2021-01-06 08:55 UTC, pau-baiget approved these changes
LGTM!!

2021-01-08 01:00 UTC, rschiu commented on gpu-counters.md
> +* [IMG Counters](img)
Done

2021-01-08 01:00 UTC, rschiu commented on _data/nav.yml
> +      - title: IMG® Counters
Done

2021-01-08 02:24 UTC, jakon2048 approved these changes

2021-01-08 18:30 UTC, merged